version: '3.7'

services:

  django:
    container_name: django
    build: .
    command: gunicorn api.wsgi:application --workers=4 --bind unix:/usr/src/app/api/app.sock
    volumes:
      - sock:/usr/src/app/api
      - static:/usr/src/app/static
    env_file:
      - ./.env

  nginx:
    container_name: nginx
    build:
      target: prod
      context: ./frontend
    ports:
      - 80:80
    volumes:
      - sock:/home/nginx/api
      - static:/home/nginx/static/static
    depends_on:
      - django

volumes:
  sock:
  static:
